### ISSUE TITLE
Slack group?

### ISSUE THREAD

**Issue by vamega** [sjsyrek/study-haskell-nyc#1]
I've created a group at: https://study-haskell-nyc.slack.com

For now if you wish to be added, just email me at <GH username> <you know what symbol> <Google's mail service> and I'll add you.

Perhaps worth adding to the README?

**Comment by sjsyrek** [comment]
There's already a Slack group ny-haskell.slack.com that is underpopulated. I appreciate the motivation, but I wonder if we really need an entirely separate Slack group when we haven't even gotten going yet?

**Comment by vamega** [comment]
Yeah, that one would probably be better.
Removed the one I created.

**Comment by sjsyrek** [comment]
👍
